"""Markdown reporter — suitable for GitHub PR comments and CI annotations."""

from __future__ import annotations

from typing import TYPE_CHECKING

from redforge.reporters.base import BaseReporter

if TYPE_CHECKING:
    from redforge.core.orchestrator import ScanReport

SEVERITY_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🟢",
    "info": "⚪",
}


class MarkdownReporter(BaseReporter):
    fmt = "markdown"
    fmt_aliases = ["md"]

    def render(self, report: ScanReport) -> str:
        s = report.score
        lines = [
            "# RedForge Scan Report",
            "",
            f"**Session:** `{report.session_id}`  ",
            f"**Target:** `{report.session.target}`  ",
            f"**Model:** `{report.session.model}`  ",
            f"**Risk Level:** **{s.risk_level}** ({s.risk_score:.1f}/10)  ",
            f"**Pass Rate:** {s.pass_rate * 100:.0f}% ({s.passed}/{s.total_probes} probes passed)  ",
            "",
            "## Summary",
            "",
            "| Severity | Count |",
            "|----------|-------|",
            f"| 🔴 Critical | {s.critical_findings} |",
            f"| 🟠 High | {s.high_findings} |",
            f"| 🟡 Medium | {s.medium_findings} |",
            f"| 🟢 Low | {s.low_findings} |",
            "",
        ]

        failures = [r for r in report.results if not r.passed]
        if failures:
            lines += ["## Findings", ""]
            for r in sorted(failures, key=lambda x: x.score, reverse=True):
                emoji = SEVERITY_EMOJI.get(r.severity, "⚪")
                lines += [
                    f"### {emoji} {r.probe_id}",
                    f"- **OWASP:** {r.owasp_id} | **MITRE:** {r.mitre_atlas}",
                    f"- **Score:** {r.score:.2f}/1.0 | **Severity:** {r.severity.upper()}",
                    f"- **Evidence:** {r.evidence}",
                    "",
                ]
        else:
            lines += ["## ✅ All Probes Passed", ""]

        lines += [
            "---",
            "*Generated by [RedForge](https://github.com/redforge/redforge) — Apache 2.0*",
        ]
        return "\n".join(lines)
